# Generated by Django 5.2.5 on 2025-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_update_team_permission_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_video_create_channels',
            field=models.BooleanField(default=False, help_text='Allows creating chat/video channels inside Eventyay Video.', verbose_name='Video: Can create channels'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_create_stages',
            field=models.BooleanField(default=False, help_text='Allows creating livestream stages inside Eventyay Video.', verbose_name='Video: Can create stages'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_direct_message',
            field=models.BooleanField(default=False, help_text='Grants permission to open new direct message conversations.', verbose_name='Video: Can send direct messages'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_manage_announcements',
            field=models.BooleanField(default=False, help_text='Allows posting announcements in the Eventyay Video interface.', verbose_name='Video: Can create announcements'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_manage_configuration',
            field=models.BooleanField(default=False, help_text='Allows editing the global Eventyay Video configuration.', verbose_name='Video: Can edit event configuration'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_manage_kiosks',
            field=models.BooleanField(default=False, help_text='Allows managing kiosk displays inside Eventyay Video.', verbose_name='Video: Can create and edit kiosks'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_manage_rooms',
            field=models.BooleanField(default=False, help_text='Allows editing and deleting rooms inside Eventyay Video.', verbose_name='Video: Can create and edit rooms'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_manage_users',
            field=models.BooleanField(default=False, help_text='Allows moderating users (ban, silence, reactivate) in Eventyay Video.', verbose_name='Video: Can message, ban, and silence users'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_view_users',
            field=models.BooleanField(default=False, help_text='Allows access to the user directory in Eventyay Video.', verbose_name='Video: Can view users'),
        ),
    ]
