# Generated by Django 5.2.5 on 2026-01-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team_can_video_create_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='landing_page_text',
        ),
    ]
    