# Generated by Django 5.2.5 on 2026-01-21 15:15

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_locale_alter_question_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkquestion',
            name='question',
            field=i18nfield.fields.I18nCharField(blank=True, max_length=800, null=True, verbose_name='Label'),
        ),
    ]
