# Generated by Django 5.2.10 on 2026-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_private_testmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive questions are not shown to customers during checkout or check-in. Unlike hidden questions (which are system-level), active controls visibility and can be toggled by event organizers.', verbose_name='Active'),
        ),
    ]
