# Generated by Django 5.2.10 on 2026-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='talks_published',
            field=models.BooleanField(default=False, verbose_name='Talk pages are published'),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_published',
            field=models.BooleanField(default=False, verbose_name='Tickets are published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='private_testmode',
            field=models.BooleanField(default=True),
        ),
    ]
