# Generated by Django 5.2.10 on 2026-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_event_talks_published_event_tickets_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='startpage_featured',
            field=models.BooleanField(default=False, verbose_name='Featured on start page'),
        ),
        migrations.AddField(
            model_name='event',
            name='startpage_visible',
            field=models.BooleanField(default=True, verbose_name='Visible on start page'),
        ),
    ]
