# Generated by Django 5.2.11 on 2026-02-17 03:55

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_streamschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_in_system',
            field=models.BooleanField(default=True, verbose_name='Show in header and footer on system pages'),
        ),
        migrations.AlterField(
            model_name='cfp',
            name='text',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_sessions_text',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='This text will be shown at the top of the featured sessions page instead of the default text. <span class="markdown-hint">You can use Markdown in this field.</span>', null=True, verbose_name='Featured sessions text'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=models.TextField(help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='comment',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='This text will be shown in the public changelog and the RSS feed. <span class="markdown-hint">You can use Markdown in this field.</span>', null=True),
        ),
        migrations.AlterField(
            model_name='speakerinformation',
            name='text',
            field=i18nfield.fields.I18nTextField(help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='speakerprofile',
            name='biography',
            field=models.TextField(blank=True, help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(blank=True, help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submissioncomment',
            name='text',
            field=models.TextField(help_text='<span class="markdown-hint">You can use Markdown in this field.</span>', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='help_text',
            field=i18nfield.fields.I18nCharField(blank=True, help_text='Will appear just like this text below the custom input field. <span class="markdown-hint">You can use Markdown in this field.</span>', max_length=800, null=True, verbose_name='help text'),
        ),
    ]
