# Generated by Django 5.2.9 on 2026-02-07 09:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_positions(apps, _schema_editor):
    """Backfill position values for existing SubmissionType instances.

    Sets position based on current default_duration ordering to maintain
    stable order and prevent NULL-related ordering issues.
    """
    SubmissionType = apps.get_model('base', 'SubmissionType')
    Event = apps.get_model('base', 'Event')

    for event in Event.objects.all():
        # Get all submission types for this event, ordered by default_duration
        types = SubmissionType.objects.filter(event=event).order_by('default_duration', 'id')

        # Assign positions starting from 1
        for position, submission_type in enumerate(types, start=1):
            submission_type.position = position
            submission_type.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_talkquestion_variant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submissiontype",
            options={"ordering": ["position", "default_duration"]},
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The position field is used to determine the order that session types are displayed in (lowest first).",
                null=True,
                verbose_name="position",
            ),
        ),
        migrations.RunPython(backfill_positions, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cfp",
            name="default_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The default session type for new submissions. Leave empty to show no pre-selected type in the CFP form.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.submissiontype",
                verbose_name="Default session type",
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('ms', 'Malay'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Chinese Simplified'), ('zh-hant', 'Chinese Traditional')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('ms', 'Malay'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Chinese Simplified'), ('zh-hant', 'Chinese Traditional')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
