# Generated by Django 5.2.11 on 2026-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_submissiontype_position_cfp_default_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Show this speaker in public list of featured speakers.'),
        ),
        migrations.AddField(
            model_name='speakerprofile',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
