# Generated by Django 5.2.11 on 2026-02-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_speakerprofile_is_featured_and_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('bn', 'Bengali'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('hi', 'Hindi'), ('gu', 'Gujarati'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('km', 'Khmer'), ('lv', 'Latvian'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Chinese Simplified'), ('zh-hant', 'Chinese Traditional')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('bn', 'Bengali'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('hi', 'Hindi'), ('gu', 'Gujarati'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('km', 'Khmer'), ('lv', 'Latvian'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Chinese Simplified'), ('zh-hant', 'Chinese Traditional')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
