# Generated by Django 5.2.12 on 2026-03-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0019_alter_event_locale_alter_user_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='allow_ignore_approval',
            field=models.BooleanField(
                default=False,
                help_text='If activated, a holder of this voucher code can buy tickets without awaiting approval by the organiser. This is applicable for products that require approval.',
                verbose_name='Allow to bypass approval',
            ),
        ),
    ]
