# Generated by Django 5.2.12 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0020_voucher_allow_ignore_approval_alter_event_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(
                choices=[
                    ('N', 'Number'),
                    ('S', 'Text (one line)'),
                    ('T', 'Multiline text'),
                    ('B', 'Confirm Checkbox'),
                    ('C', 'Radio button (Choose one option)'),
                    ('L', 'Dropdown (Choose one option)'),
                    ('M', 'Checkbox (Choose one or several options)'),
                    ('F', 'File upload'),
                    ('D', 'Date'),
                    ('H', 'Time'),
                    ('W', 'Date and time'),
                    ('CC', 'Country code (ISO 3166-1 alpha-2)'),
                    ('TEL', 'Phone number'),
                    ('DES', 'Text field'),
                ],
                max_length=5,
                verbose_name='Type',
            ),
        ),
    ]
