# Generated by Django 5.2.12 on 2026-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_event_currency_alter_giftcard_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_user_variation_change',
            field=models.BooleanField(default=False, help_text='If this is checked, customers can switch between variations of this product in their order details.', verbose_name='Allow customers to change product variations'),
        ),
    ]
