# Generated by Django 5.2.12 on 2026-04-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_product_allow_user_variation_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='featured_sessions_text',
        ),
    ]
