# Generated by Django 5.2.12 on 2026-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_event_featured_sessions_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('generic', 'Generic resource'), ('slides', 'Slides')], default='generic', max_length=7),
        ),
        migrations.AddField(
            model_name='talkquestion',
            name='import_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Import key'),
        ),
        migrations.AddField(
            model_name='talkquestion',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Imported fields are managed automatically and hidden from normal form configuration.', verbose_name='Imported field'),
        ),
        migrations.AddConstraint(
            model_name='talkquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key__isnull', False), models.Q(('import_key', ''), _negated=True)), fields=('event', 'target', 'import_key'), name='unique_import_question_per_event_target'),
        ),
    ]
