# Generated by Django 5.2.14 on 2026-06-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_talkquestion_dependency_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum price a user can enter. If left empty, there is no upper limit.', max_digits=7, null=True, verbose_name='Maximum price'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum price a user has to enter. If left empty, the default price will be used as the minimum.', max_digits=7, null=True, verbose_name='Minimum price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_price',
            field=models.BooleanField(default=False, help_text='If this option is active, your users can choose the price themselves. The minimum and maximum prices can be configured below. If not configured, the default price is used as the minimum. You could use this e.g. to collect additional donations for your event. This is currently not supported for products that are bought as an add-on to other products.', verbose_name='Free price input'),
        ),
    ]
