# Generated by Django 5.2.14 on 2026-06-06 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_free_price_max_product_free_price_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='base.organizer', verbose_name='Organizer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_organizers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Organizer follower',
                'verbose_name_plural': 'Organizer followers',
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('user', 'organizer'), name='unique_organizer_follower')],
            },
        ),
    ]
