# Generated by Django 5.2.13 on 2026-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_organizerfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_unscheduled',
            field=models.BooleanField(default=False, help_text='If enabled, this room will not appear in the schedule or schedule-editor and cannot be linked to talk sessions.', verbose_name='Unscheduled room'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_video_manage_polls_questions',
            field=models.BooleanField(default=False, help_text='Allows managing polls and questions in rooms inside Eventyay Video.', verbose_name='Video: Can manage polls and questions'),
        ),
    ]
