# Generated by Django 6.0.7 on 2026-08-17 08:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_team_teamshifts_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(decimal_places=2, help_text='If this product has multiple variations, you can set different prices for each of the variations. If a variation does not have a special price or if you do not have variations, this price will be used.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Default price'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Default price'),
        ),
        migrations.AlterField(
            model_name='team',
            name='force_hide_speaker_emails',
            field=models.BooleanField(default=False, help_text='When enabled, this team cannot see speaker email addresses in organiser views, exports, or API responses, but can still see other speaker details (unless “Always hide speaker details” is also enabled).', verbose_name='Always hide speaker emails only'),
        ),
        migrations.AlterField(
            model_name='team',
            name='force_hide_speaker_names',
            field=models.BooleanField(default=False, help_text='Normally, speaker anonymisation follows each event’s review settings. When enabled, this team <strong>always</strong> hides speaker names and details in proposal and review views, exports, and API responses — even if the event review phase would otherwise show them. Applies together with any track limits.', verbose_name='Always hide speaker details'),
        ),
        migrations.AlterField(
            model_name='team',
            name='limit_tracks',
            field=models.ManyToManyField(blank=True, help_text='Limit this team to the selected tracks. Members only see proposals, sessions, reviews, speakers, schedule data, exports, and API results for those tracks. Leave empty for access to all tracks in the team’s events. Configure tracks per event below.', to='base.track', verbose_name='Restrict access to tracks'),
        ),
    ]
