# Generated by Django 6.0.7 on 2026-08-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_global_plugin_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='base.organizer', verbose_name='Default organizer'),
        ),
    ]
