# Generated by Django 6.0.7 on 2026-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_user_default_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', '\u200eDeutsch (German)'), ('de-formal', '\u200eDeutsch (German (formal))'), ('ar', '\u200eاَلْعَرَبِيَّةُ (Arabic)'), ('bg', '\u200eБългарски (Bulgarian)'), ('bn', '\u200eবাংলা (Bengali)'), ('ca', '\u200eCatalà (Catalan)'), ('cs', '\u200eČeština (Czech)'), ('da', '\u200eDansk (Danish)'), ('el', '\u200eΕλληνικά (Greek)'), ('es', '\u200eEspañol (Spanish)'), ('fa-ir', '\u200eقارسی (Persian)'), ('fi', '\u200eSuomi (Finnish)'), ('fr', '\u200eFrançais (French)'), ('hu', '\u200eMagyar (Hungarian)'), ('hi', '\u200eहिन्दी (Hindi)'), ('gu', '\u200eગુજરાતી (Gujarati)'), ('id', '\u200eBahasa Indonesia (Indonesian)'), ('it', '\u200eItaliano (Italian)'), ('ja-jp', '\u200e日本語 (Japanese)'), ('ko', '\u200e한국어 (Korean)'), ('km', '\u200eខ្មែរ (Khmer)'), ('lv', '\u200eLatviešu (Latvian)'), ('ms', '\u200eBahasa Melayu (Malay)'), ('ml', '\u200eമലയാളം (Malayalam)'), ('mr', '\u200eमराठी (Marathi)'), ('nb-no', '\u200eNorsk bokmål (Norwegian Bokmål)'), ('nl', '\u200eNederlands (Dutch)'), ('nl-informal', '\u200eNederlands (Dutch (informal))'), ('pl', '\u200ePolski (Polish)'), ('pl-informal', '\u200ePolski (nieformalny) (Polish (informal))'), ('pt-br', '\u200ePortuguês brasileiro (Brazilian Portuguese)'), ('pt-pt', '\u200ePortuguês (Portuguese)'), ('ro', '\u200eRomână (Romanian)'), ('ru', '\u200eРусский (Russian)'), ('si', '\u200eසිංහල (Sinhala)'), ('sl', '\u200eSlovenščina (Slovenian)'), ('sv', '\u200eSvenska (Swedish)'), ('sw', '\u200eKiswahili (Swahili)'), ('ta', '\u200eதமிழ் (Tamil)'), ('te', '\u200eతెలుగు (Telugu)'), ('th', '\u200eไทย (Thai)'), ('tr', '\u200eTürkçe (Turkish)'), ('uk', '\u200eУкраїнська (Ukrainian)'), ('ur', '\u200eاردو (Urdu)'), ('vi', '\u200eTiếng Việt (Vietnamese)'), ('zh-hans', '\u200e简体中文 (Chinese Simplified)'), ('zh-hant', '\u200e繁體中文 (Chinese Traditional)')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', '\u200eDeutsch (German)'), ('de-formal', '\u200eDeutsch (German (formal))'), ('ar', '\u200eاَلْعَرَبِيَّةُ (Arabic)'), ('bg', '\u200eБългарски (Bulgarian)'), ('bn', '\u200eবাংলা (Bengali)'), ('ca', '\u200eCatalà (Catalan)'), ('cs', '\u200eČeština (Czech)'), ('da', '\u200eDansk (Danish)'), ('el', '\u200eΕλληνικά (Greek)'), ('es', '\u200eEspañol (Spanish)'), ('fa-ir', '\u200eقارسی (Persian)'), ('fi', '\u200eSuomi (Finnish)'), ('fr', '\u200eFrançais (French)'), ('hu', '\u200eMagyar (Hungarian)'), ('hi', '\u200eहिन्दी (Hindi)'), ('gu', '\u200eગુજરાતી (Gujarati)'), ('id', '\u200eBahasa Indonesia (Indonesian)'), ('it', '\u200eItaliano (Italian)'), ('ja-jp', '\u200e日本語 (Japanese)'), ('ko', '\u200e한국어 (Korean)'), ('km', '\u200eខ្មែរ (Khmer)'), ('lv', '\u200eLatviešu (Latvian)'), ('ms', '\u200eBahasa Melayu (Malay)'), ('ml', '\u200eമലയാളം (Malayalam)'), ('mr', '\u200eमराठी (Marathi)'), ('nb-no', '\u200eNorsk bokmål (Norwegian Bokmål)'), ('nl', '\u200eNederlands (Dutch)'), ('nl-informal', '\u200eNederlands (Dutch (informal))'), ('pl', '\u200ePolski (Polish)'), ('pl-informal', '\u200ePolski (nieformalny) (Polish (informal))'), ('pt-br', '\u200ePortuguês brasileiro (Brazilian Portuguese)'), ('pt-pt', '\u200ePortuguês (Portuguese)'), ('ro', '\u200eRomână (Romanian)'), ('ru', '\u200eРусский (Russian)'), ('si', '\u200eසිංහල (Sinhala)'), ('sl', '\u200eSlovenščina (Slovenian)'), ('sv', '\u200eSvenska (Swedish)'), ('sw', '\u200eKiswahili (Swahili)'), ('ta', '\u200eதமிழ் (Tamil)'), ('te', '\u200eతెలుగు (Telugu)'), ('th', '\u200eไทย (Thai)'), ('tr', '\u200eTürkçe (Turkish)'), ('uk', '\u200eУкраїнська (Ukrainian)'), ('ur', '\u200eاردو (Urdu)'), ('vi', '\u200eTiếng Việt (Vietnamese)'), ('zh-hans', '\u200e简体中文 (Chinese Simplified)'), ('zh-hant', '\u200e繁體中文 (Chinese Traditional)')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
