# Generated by Django 6.0.7 on 2026-08-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_locale_choices_native_names'),
    ]

    operations = [
        # Child tables first so unique_together on ExhibitorStaff is not altered after its FKs are gone.
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.DeleteModel(
            name='ExhibitorSocialMediaLink',
        ),
        migrations.DeleteModel(
            name='ExhibitorLink',
        ),
        migrations.DeleteModel(
            name='ExhibitorStaff',
        ),
        migrations.DeleteModel(
            name='ExhibitorView',
        ),
        migrations.DeleteModel(
            name='Exhibitor',
        ),
    ]
