# Generated by Django 6.0.7 on 2026-08-21 16:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_video_poster_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(decimal_places=2, help_text='If this product has multiple variations, you can set different prices for each of the variations. If a variation does not have a special price or if you do not have variations, this price will be used.', max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Default price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum price a user can enter. If left empty, there is no upper limit.', max_digits=13, null=True, verbose_name='Maximum price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum price a user has to enter. If left empty, the default price will be used as the minimum.', max_digits=13, null=True, verbose_name='Minimum price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this will be displayed next to the current price to show that the current price is a discounted one. This is just a cosmetic setting and will not actually impact pricing.', max_digits=13, null=True, verbose_name='Original price'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Default price'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this will be displayed next to the current price to show that the current price is a discounted one. This is just a cosmetic setting and will not actually impact pricing.', max_digits=13, null=True, verbose_name='Original price'),
        ),
        migrations.AlterField(
            model_name='subeventproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='subeventproductvariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
