# Generated by Django 6.0.7 on 2026-08-20 14:54

import django.db.models.deletion
import eventyay.base.models.mixins
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_price_max_digits_currency_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banned_users',
            field=models.ManyToManyField(blank=True, help_text='Users who are banned from submitting feedback or interacting with this event.', related_name='banned_events', to=settings.AUTH_USER_MODEL, verbose_name='Banned users'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If disabled, the feedback is anonymous to the speaker and not shown publicly.', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Indicates whether this feedback has been reported by a user.', verbose_name='Is reported'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.feedback', verbose_name='Parent feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='report_count',
            field=models.IntegerField(default=0, help_text='Number of times this feedback has been reported.', verbose_name='Report count'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending Review'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='FeedbackReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_upvote', models.BooleanField(default=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='base.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feedback', 'user')},
            },
            bases=(eventyay.base.models.mixins.LogMixin, eventyay.base.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
