# Generated by Django 6.0.7 on 2026-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_gmailoauthcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmail',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Drafts are kept out of the outbox and are never sent until they are moved there.', verbose_name='Draft'),
        ),
    ]
