# Generated by Django 6.0.7 on 2026-08-25 13:16

import eventyay.base.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_page_text_markdown_to_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='We recommend uploading a square image at least 400px wide.', null=True, upload_to=eventyay.base.models.auth.profile_picture_path, verbose_name='Account profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_thumbnail_tiny',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
