#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Eventyay documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# The eventyay project should be installed to virtual env (default behavior of `uv`)

# Set minimal config file for documentation builds
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'eventyay.config.settings')
# Use 'testing' environment to turn off rich logging.
os.environ.setdefault('EVY_RUNNING_ENVIRONMENT', 'testing')
# Tell the application settings module to use in-memory infrastructure while
# autodoc imports Django modules.
os.environ.setdefault('EVY_DOCS_BUILD', '1')

import django

# Configure Django and override LOGGING settings for documentation builds
# This must be done AFTER django.setup() to avoid triggering early settings initialization
try:
    django.setup()
except Exception as e:
    # Documentation build can continue even if Django setup fails
    print(f"Warning: Django setup failed: {e}", file=sys.stderr)

try:
    import enchant

    enchant.Dict('en_US')
    HAS_PYENCHANT = True
except Exception:
    HAS_PYENCHANT = False

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinxcontrib.httpdomain',
    'sphinxcontrib.images',
    'sphinxemoji.sphinxemoji',
    'sphinx_rtd_theme',
]
if HAS_PYENCHANT:
    extensions.append('sphinxcontrib.spelling')

# Configure autodoc to continue on import errors
# We want to document what works, and show warnings for what doesn't
autodoc_default_options = {
    'members': True,
    'undoc-members': False,
    'show-inheritance': True,
}
autodoc_typehints = 'none'

# Don't fail the build on autodoc import errors
autodoc_warningiserror = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Eventyay'
copyright = '2026 Apache 2.0 License by contributors'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# Note: version and release are read by Sphinx from this module's namespace
try:
    from eventyay import __version__
    version = '.'.join(__version__.split('.')[:2])
    release = __version__
except ImportError:
    version = '1.0'
    release = '1.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build',
    '.venv',
    'venv',
    # These sources are included by unified replacement pages. Excluding the
    # originals prevents their labels from being parsed a second time.
    'admin/config.rst',
    'development/unified_architecture.rst',
    'talk/user/sessions.rst',
    'user/events/create.rst',
]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = ""

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'logo_only': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add custom CSS files
html_css_files = [
    'eventyay_custom.css',
]

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'images/eventyay-logo.svg'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = 'images/favicon.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [
    '_static',
]
# Try to add fonts if they exist
if os.path.exists(os.path.abspath('../app/eventyay/static/fonts/')):
    html_static_path.append(os.path.abspath('../app/eventyay/static/fonts/'))
if os.path.exists(os.path.abspath('../app/eventyay/static/fontawesome/fonts/')):
    html_static_path.append(os.path.abspath('../app/eventyay/static/fontawesome/fonts/'))

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'eventyaydoc'

html_theme = 'sphinx_rtd_theme'
# html_theme_path = [os.path.abspath('_themes')]


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('index', 'eventyay.tex', 'Eventyay Documentation', 'FOSSASIA', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [('index', 'eventyay', 'Eventyay Documentation', ['FOSSASIA'], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        'index',
        'eventyay',
        'Eventyay Documentation',
        'FOSSASIA',
        'eventyay',
        'Open source event management platform',
        'Miscellaneous',
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False


images_config = {'default_image_width': '250px'}

linkcheck_ignore = [
    r'http://localhost.*',
    r'.*yourdomain.*',
    r'https://en.wikipedia.org',
    'https://eventyay.com/',
]

# -- Options for Spelling output ------------------------------------------
if HAS_PYENCHANT:
    # String specifying the language, as understood by PyEnchant and enchant.
    # Defaults to en_US for US English.
    spelling_lang = 'en_US'

    # String specifying a file containing a list of words known to be spelled
    # correctly but that do not appear in the language dictionary selected by
    # spelling_lang. The file should contain one word per line.
    spelling_word_list_filename = 'spelling_wordlist.txt'

    # Boolean controlling whether suggestions for misspelled words are printed.
    # Defaults to False.
    spelling_show_suggestions = True

    # List of filter classes to be added to the tokenizer that produces words to be checked.
    spelling_filters = ['checkin_filter.CheckinFilter']


def autodoc_skip_member(app, what, name, obj, skip, options):
    """
    Skip URL descriptor attributes that cause autodoc issues.
    
    Django urlman creates nested 'urls' classes as descriptors. These don't have
    proper __objclass__ attributes and cause autodoc to fail when trying to document them.
    We skip these entirely as they are implementation details.
    """
    # Skip all urlman URL descriptor attributes
    if name in ('urls', 'orga_urls', 'api_urls', 'tickets_urls'):
        return True
    # Also skip any attribute ending with _urls
    if name.endswith('_urls'):
        return True

    # Avoid evaluating QuerySets during introspection (repr() can hit the DB).
    try:
        from django.db.models.query import QuerySet as DjangoQuerySet
        if isinstance(obj, DjangoQuerySet):
            return True
    except ImportError:
        return skip


def setup(app):
    """Setup function for Sphinx."""
    app.connect('autodoc-skip-member', autodoc_skip_member)
