# Generated by Django 5.2

import django.contrib.postgres.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_emailqueue_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueuefilter',
            name='individual_attendees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='emailqueuefilter',
            name='recipients',
            field=models.CharField(
                blank=True,
                choices=[
                    ('orders', 'Orders'),
                    ('attendees', 'Attendees'),
                    ('both', 'Both'),
                    ('individual', 'Individual'),
                ],
                default='orders',
                max_length=10,
            ),
        ),
    ]
