# Generated by Django 5.2.12 on 2026-03-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgelayout',
            name='allow_customization',
            field=models.BooleanField(default=False, verbose_name='Allow badge customization'),
        ),
        migrations.AddField(
            model_name='badgelayout',
            name='ask_user_fields',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
