# Generated by Django 5.2.12 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_badgelayout_allow_badge_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgelayout',
            name='required_badge_fields',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
